#!/bin/bash

MIN_WIDTH=10
cc='#'
width=80
fill=' '

usage() {
    echo "usage: commentize -c [comment character] -w [width, greater than $MIN_WIDTH] -f [fill character] -s [string to commentize]"
}

while getopts :c:w:s:f: FLAG; do
    case $FLAG in
        c)
            cc=$OPTARG
            if (( ${#cc} != 1)); then
                echo "-c : must be a single character"
                exit 1;
            fi
            ;;
        w)
            width=$OPTARG
            if [ $width -le $MIN_WIDTH ]; then
                usage
                exit 1
            fi
            ;;
        s)
            str=$OPTARG
            ;;
        f)
            fill=$OPTARG
            if (( ${#fill} != 1)); then
                echo "-f : must be a single character"
                exit 1;
            fi
            ;;
        \?)
            usage
            exit 1
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if [ ! "$str" ]; then
    str=$(cat)
fi

str=`echo "$str" | tr ' ' 'ꌴ'`

printf "%${width}s\n" | tr ' ' "$cc"

m=$(($width-8))
line=`printf "%${m}s" | tr ' ' "$fill"`

while read -r j; do
    q=$((${#j}/$m))
    r=$((${#j}%$m))

    if [ $r -gt 0 ]; then
        q=$(($q+1))
    fi

    for i in `seq $q`; do
        x=${j:$(($(($i-1))*$m)):$m}
        printf "$cc$cc  %s  %s$cc$cc\n" "${j:$(($(($i-1))*$m)):$m}" "${line:${#x}}" | tr 'ꌴ' ' '
    done
done <<< "$str"

printf "%${width}s\n" | tr ' ' "$cc"
