#!/bin/bash

cc='#'
width=80

usage() {
    echo 'usage: commentize -c [comment character] -w [width] -s [string to commentize]'
}

while getopts :c:w:s: FLAG; do
    case $FLAG in
        c)
            cc=$OPTARG
            ;;
        w)
            width=$OPTARG
            ;;
        s)
            str=$OPTARG
            ;;
        h)
            echo "-c " 
            exit 1
            ;;
        \?)
            usage
            exit 1
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done


if [ ! $str ]; then
    usage
    exit 1
fi


m=$(($width-8))
q=$((${#str}/$m))
r=$((${#str}%$m))

if [ $r -gt 0 ]; then
    q=$(($q+1))
fi

seq -f $cc -s '' $width; echo
line=`seq -f ' ' -s '' $m`

for i in `seq $q`; do
    x=${str:$(($(($i-1))*$m)):$m}
    printf "$cc$cc  %s %s $cc$cc\n" "${str:$(($(($i-1))*$m)):$m}" "${line:${#x}}"
done
seq -f $cc -s '' $width; echo

